---
micronaut:
  application:
    name: sample
  security:
    enabled: true
#    server:
#        port: 9000
---
conferences:
    mongo:
        database: nextbuild
        collection: conferences
---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
