---
micronaut:
    application:
        name: nextbuild
    server:
        port: 8080
---
consul:
  client:
    registration:
      enabled: false
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
